name: Test all Solutions

on:
  push:

jobs:
  build:
    name: Test Solutions
    runs-on: ubuntu-latest

    steps:

      - name: ğŸ§° Checkout
        uses: actions/checkout@v4

      - name: â¬‡ï¸ Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'

      - name: â¬‡ï¸ Setup Gradle
        uses: gradle/gradle-build-action@v2.11.1

      - name: ğŸ› ï¸ Build and Test ğŸ§ª
        run: ./gradlew test