name: Test all Solutions

on:
  push:


jobs:
  build:
    name: Test Solutions
    runs-on: ubuntu-latest

    steps:

      - name: ğŸ§° Checkout
        uses: actions/checkout@v4

      - name: â¬‡ï¸ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: â¬‡ï¸ Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: ğŸ› ï¸ Build and Test ğŸ§ª
        run: ./gradlew test